on:
  #push:
  pull_request:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: |
          echo "github.sha = ${{ github.sha }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref.name = ${{ github.ref.name }}"
          echo "github.ref.type = ${{ github.type }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event.pull_request.head.ref = ${{ github.event.pull_request.head.ref }}"
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
